controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

create_user:
    path: /register
    controller: App\Controller\UserController::createUser
    methods: POST

login_user:
    path: /login
    controller: App\Controller\UserController::login
    methods: POST

